# Structure du rôle : roles/iis_stop/

# roles/iis_stop/tasks/main.yml
---
- name: Arrêter les pools d'applications
  win_iis_webapppool:
    name: "{{ item }}"
    state: stopped
  loop: "{{ iis_app_pools | default(['DefaultAppPool']) }}"

- name: Arrêter le site web par défaut
  win_iis_website:
    name: "{{ iis_default_site_name | default('Default Web Site') }}"
    state: stopped

- name: Arrêter le service World Wide Web Publishing Service
  win_service:
    name: W3SVC
    state: stopped

- name: Arrêter le service IIS Admin Service
  win_service:
    name: IISADMIN
    state: stopped

- name: Vérifier que les services IIS sont arrêtés
  win_service_info:
    name: "{{ item }}"
  loop:
    - W3SVC
    - IISADMIN
  register: iis_services_status

- name: Afficher le statut d'arrêt d'IIS
  debug:
    msg: "IIS est correctement arrêté"
  when: iis_services_status.results | selectattr('services.0.state', 'equalto', 'stopped') | list | length == 2
