---
# tasks file for windows_dotnet_aspcore_install
- name: Check Architecture
  win_shell: $env:PROCESSOR_ARCHITECTURE
  register: architecture_result
  changed_when: false

- name: Define Architecture for Download
  set_fact:
    dotnet_arch: "{{ 
      'x64' if architecture_result.stdout | trim == 'AMD64' else 
      'x86' if architecture_result.stdout | trim == 'X86' else 
      'arm64' if architecture_result.stdout | trim == 'ARM64' else 
      'x64' 
    }}"

- name: Check version of Runtime
  ansible.builtin.assert:
    that:
      - dotnet_version in aspnetcore_versions
      - runtime_version in aspnetcore_versions[dotnet_version].runtimes
    fail_msg: "Version de runtime non supportée. Versions disponibles : {{ aspnetcore_versions[dotnet_version].runtimes.keys() | list }}"

- name: Information of download
  set_fact:
    runtime_download_pr_id: "{{ aspnetcore_versions[dotnet_version].runtimes[runtime_version].download_pr_id }}"
    runtime_download_hash: "{{ aspnetcore_versions[dotnet_version].runtimes[runtime_version].download_hash }}"

- name: Build link ASP.NET Core Runtime
  set_fact:
    runtime_download_url: "https://download.visualstudio.microsoft.com/download/pr/{{ runtime_download_pr_id }}/{{ runtime_download_hash }}/dotnet-runtime-{{ runtime_version }}-win-{{ dotnet_arch }}.exe"

- name: Create temp folder
  win_file:
    path: C:\Temp
    state: directory

- name: Download ASP.NET Core Runtime
  win_uri:
    url: "{{ runtime_download_url }}"
    dest: "C:\\Temp\\aspnetcore-runtime-{{ runtime_version }}-win-{{ dotnet_arch }}.exe"
    creates: "C:\\Temp\\aspnetcore-runtime-{{ runtime_version }}-win-{{ dotnet_arch }}.exe"

- name: Install ASP.NET Core Runtime
  win_command: >
    C:\Temp\aspnetcore-runtime-{{ runtime_version }}-win-{{ dotnet_arch }}.exe 
      /install
      /quiet 
      /norestart

- name: Check runtime ASP.NET Core
  win_command: dotnet --list-runtimes
  register: dotnet_runtimes
  changed_when: false

- name: Informations of installations
  debug:
     msg:
      - "Architecture : {{ dotnet_arch }}"
      - "Version runtime installée : {{ runtime_version }}"
      - "URL de téléchargement : {{ runtime_download_url }}"
      - "Runtimes installés : {{ dotnet_runtimes.stdout_lines }}"

- name: Clean-up folder installation
  win_file:
    path: "C:\\Temp\\aspnetcore-runtime-{{ runtime_version }}-win-{{ dotnet_arch }}.exe"
    state: absent