# tasks file for redis-management
---
- name: Vérifier que l'action Redis est valide
  fail:
    msg: "Action '{{ action_redis }}' non supportée. Actions autorisées: {{ redis_actions_allowed | join(', ') }}"
  when: action_redis not in redis_actions_allowed

- name: Vérifier le statut actuel du service Redis
  shell: systemctl status {{ redis_service_name }} | grep "Active:"
  register: service_result
  failed_when: false
  changed_when: false
  when: redis_check_status | bool

- name: Afficher le statut actuel de Redis
  debug:
    msg: "Statut Redis: {{ service_result.stdout | default('Non vérifié') }}"
  when: redis_check_status | bool

- name: Déclencher l'action Redis si conditions remplies
  debug:
    msg: "Déclenchement de l'action '{{ action_redis }}' pour Redis"
  when: >
    (service_result.stdout is not defined or 
     service_result.stdout | length == 0 or
     ('inactive' in service_result.stdout and action_redis == 'start') or
     ('active' in service_result.stdout and action_redis in ['stop', 'restart', 'reload']))
  notify: execute redis action
  changed_when: true

- name: Forcer l'exécution des handlers
  meta: flush_handlers