---
# vars file for iis_deploy
# Configuration par défaut
iis_deploy_app_name: "DefaultAppName"
iis_deploy_physical_path: "C:\\inetpub\\wwwroot\\{{ iis_deploy_app_name }}"
iis_deploy_site_name: "Default Web Site"
iis_deploy_app_pool_name: "{{ iis_deploy_app_name }}_pool"
iis_deploy_app_path: "/{{ iis_deploy_app_name }}"
iis_deploy_port: 80
iis_deploy_binding_info: "*:{{ iis_deploy_port }}:"

# Configuration Artifactory
artifactory_url: "http://artifactory.example.com/artifactory"
artifactory_repository: "webapp-releases"
artifactory_username: ""
artifactory_password: ""
artifactory_artifact_path: "{{ iis_deploy_app_name }}/{{ iis_deploy_version }}/{{ iis_deploy_app_name }}-{{ iis_deploy_version }}.zip"
iis_deploy_version: "latest"
artifactory_api_key: ""

# Environnement et configuration de l'application
iis_deploy_app_environment: "production"
iis_deploy_dotnet_version: "v4.0"
iis_deploy_enable_32bit: false
iis_deploy_managed_pipeline_mode: "Integrated"
iis_deploy_identity_type: "ApplicationPoolIdentity"  # Options: LocalSystem, NetworkService, ApplicationPoolIdentity, SpecificUser
iis_deploy_username: ""  # Utilisé uniquement si identity_type est SpecificUser
iis_deploy_password: ""  # Utilisé uniquement si identity_type est SpecificUser

# Configuration du site web
iis_deploy_site_bindings:
  - protocol: "http"
    binding_information: "{{ iis_deploy_binding_info }}"
    ssl_flags: 0

# Configuration avancée
iis_deploy_idle_timeout_minutes: 20
iis_deploy_max_processes: 1
iis_deploy_web_config_transform: false

# Options de nettoyage
iis_deploy_clean_before_deploy: true
iis_deploy_keep_versions: 3  # Nombre de versions précédentes à conserver