galaxy_info:
  author: "A&ECoding"
  description: "Rôle Ansible to sign csr to CA Authority (used with Autoritecertification)"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - linux
    - csr
    - ca
dependencies: []