---
- name: "Status - État des services (Windows)"
  win_shell: |
    cd "{{ project_path }}"
    echo "=== Services ==="
    docker-compose ps
  when: ansible_os_family == "Windows"
  register: status_output_windows

- name: "Status - État des services (Linux)"
  shell: |
    cd "{{ project_path }}"
    echo "=== Services ==="
    docker-compose ps
  when: ansible_os_family != "Windows"
  register: status_output_linux

- name: "Status - Affichage"
  debug:
    msg: "{{ status_output_windows.stdout | default('Statut non disponible') }}"

- name: "Status - Affichage"
  debug:
    msg: "{{ status_output_linux.stdout | default('Statut non disponible') }}"