---
# roles/security_report/tasks/security_updates.yml
- name: Check for security updates (Debian/Ubuntu)
  shell: |
    apt list --upgradable 2>/dev/null | grep -i security | wc -l
  register: debian_security_updates
  when: ansible_os_family == "Debian"
  changed_when: false
  failed_when: false

- name: List available security updates (Debian/Ubuntu)
  shell: |
    apt list --upgradable 2>/dev/null | grep -i security
  register: debian_security_list
  when: ansible_os_family == "Debian"
  changed_when: false
  failed_when: false

- name: Check for security updates (RedHat/CentOS)
  shell: |
    yum --security check-update | grep -c "needed for security" || echo "0"
  register: redhat_security_updates
  when: ansible_os_family == "RedHat"
  changed_when: false
  failed_when: false

- name: List available security updates (RedHat/CentOS)
  shell: |
    yum --security check-update
  register: redhat_security_list
  when: ansible_os_family == "RedHat"
  changed_when: false
  failed_when: false