---
- name: restart_homeassistant
  uri:
    url: "http://{{ ha_host }}:{{ ha_port }}/api/services/homeassistant/restart"
    method: POST
    headers:
      Authorization: "Bearer {{ ha_long_lived_token }}"
      Content-Type: "application/json"
    status_code: 200
  when: ha_long_lived_token is defined and ha_long_lived_token != ""
  ignore_errors: yes

# Alternative si pas de token : redémarrage via API publique (si activée)
## eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwMWFmYmUxYWI1YWY0NWE0YmJkZGRiM2E1YTk4YWUwZiIsImlhdCI6MTc1MzMwNTY1MiwiZXhwIjoyMDY4NjY1NjUyfQ.7GaVHZdy67K51dFrLn3UUXwNUD8v7wXxQwzP8pyPy-s
- name: restart_homeassistant_fallback
  uri:
    url: "http://{{ ha_host }}:{{ ha_port }}/api/services/homeassistant/restart"
    method: POST
    headers:
      Content-Type: "application/json"
    status_code: [200, 401]
  when: ha_long_lived_token is not defined or ha_long_lived_token == ""
  ignore_errors: yes