---
galaxy_info:
  author: "A&ECoding"
  description: "Rôle Ansible to Delete MSXML on Windows"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - -e "msxml_version=4.0 msxml_remove=true" -e "msxml_version=4.0 msxml_remove=false"
dependencies: []