---
# tasks file for autoritecertification_install
- name: Create folder CA
  file:
    path: "{{ ca_dir }}"
    state: directory
    mode: '0755'

- name: Generate a private key CA
  command: openssl genrsa -out {{ ca_key_file }} 4096
  args:
    creates: "{{ ca_key_file }}"

- name: Generate certificat of CA
  command: >
    openssl req -x509 -new -nodes -key {{ ca_key_file }}
    -sha256 -days {{ ca_validity_days }} -out {{ ca_cert_file }}
    -subj "/C={{ ca_country }}/ST={{ ca_state }}/L={{ ca_locality }}/O={{ ca_organization }}/OU={{ ca_organizational_unit }}/CN={{ ca_common_name }}"
  args:
    creates: "{{ ca_cert_file }}"
