---
# tasks file for iis_deploy
- name: "Inclure les variables spécifiques à la plateforme"
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Windows"

- name: "Vérifier que le système d'exploitation est Windows"
  fail:
    msg: "Ce rôle ne peut être exécuté que sur des serveurs Windows"
  when: ansible_os_family != "Windows"

- name: "Inclure les tâches d'installation des prérequis"
  include_tasks: install_prerequisites.yml
  tags: 
    - install
    - prerequisites

- name: "Inclure les tâches de téléchargement des artefacts"
  include_tasks: download_artifact.yml
  tags:
    - download
    - artifact

- name: "Inclure les tâches de configuration IIS"
  include_tasks: configure_iis.yml
  tags:
    - configure
    - iis

- name: "Inclure les tâches de déploiement d'application"
  include_tasks: deploy_application.yml
  tags:
    - deploy
    - application