---
galaxy_info:
  author: A&E Coding
  description: Rôle pour gérer le service Apache HTTP Server (start, stop, restart, reload, graceful)
  company: A&E Coding
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - '18.04'
        - '20.04'
        - '22.04'
    - name: CentOS
      versions:
        - '7'
        - '8'
    - name: RedHat
      versions:
        - '7'
        - '8'
        - '9'
    - name: Rocky
      versions:
        - '8'
        - '9'
    - name: AlmaLinux
      versions:
        - '8'
        - '9'
  galaxy_tags:
    - apache
    - httpd
    - webserver
    - service
    - management

dependencies: []