---
- name: Télécharger Ollama depuis le site officiel
  ansible.windows.win_get_url:
    url: "https://ollama.com/download/OllamaSetup.exe"
    dest: "C:\\Temp\\OllamaInstaller.exe"

- name: Installer Ollama en mode silencieux
  ansible.windows.win_shell: "C:\\Temp\\OllamaInstaller.exe /DIR={{ ollama_target_path }}"
  register: ollama_install
  changed_when: "'installation' in ollama_install.stdout"
