---
# tasks file for windows_ollama_install
- name: Télécharger et installer Ollama en mode silencieux
  include_tasks: download_install.yml

- name: Détecter le chemin d’installation d’Ollama
  include_tasks: detect_ollama_path.yml

# - name: Déplacer Ollama vers le dossier cible
#   include_tasks: move_ollama.yml
#   when: ollama_path.stdout is defined

# - name: Mettre à jour le PATH pour Ollama
#   include_tasks: update_path.yml
