---
- name: Ajouter Ollama au PATH
  ansible.windows.win_shell: |
    $path = [System.Environment]::GetEnvironmentVariable("Path", [System.EnvironmentVariableTarget]::Machine)
    if (-not $path.Contains("{{ ollama_target_path }}")) {
        [System.Environment]::SetEnvironmentVariable("Path", $path + ";{{ ollama_target_path }}", [System.EnvironmentVariableTarget]::Machine)
    }
  register: path_update
  changed_when: "'updated' in path_update.stdout"

- name: Vérifier si le PATH contient le nouveau chemin
  ansible.windows.win_shell: |
    if ($env:Path -match "{{ ollama_target_path }}") { Write-Output "updated" }
  register: path_check
  changed_when: false

- name: Arrêter le playbook si le PATH n’a pas été mis à jour
  fail:
    msg: "La mise à jour du PATH a échoué."
  when: path_check.stdout != "updated"
