galaxy_info:
  author: Votre nom
  description: Rôle pour arrêter IIS sur Windows Server
  company: Votre entreprise
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2012R2
        - 2016
        - 2019
        - 2022
  galaxy_tags:
    - windows
    - iis
    - webserver

dependencies: []