galaxy_info:
  author: "A&ECoding"
  description: Rôle pour déployer des services Windows depuis Artifactory
  company: A&ECoding
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2012R2
        - 2016
        - 2019
        - 2022
  galaxy_tags:
    - windows
    - service
    - deployment
    - artifactory

dependencies: []