galaxy_info:
  author: "A&ECoding"
  description: "Rôle Ansible to delete docker on windows"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - docker
    - delete
dependencies: []
