---
# vars file for iis-deploy-v2
# Configuration Artifactory
artifactory_base_url: ""
artifactory_username: ""
artifactory_password: ""
artifactory_repository: ""
package_filename: ""
artifactory_package_url: "{{ artifactory_base_url }}/{{ artifactory_repository }}/{{ package_filename }}"

# Configuration de déploiement
deploy_temp_dir: "C:\\temp\\deploy"
deploy_destination_path: "C:\\inetpub\\wwwroot"
force_download: true
download_timeout: 300
delete_package_after_extract: false
cleanup_temp_files: true

# Configuration de sauvegarde
create_backup: true
backup_path: "C:\\backup"

# Configuration IIS
site_name: ""
site_port: 80
site_ip: "*"
site_hostname: ""
app_pool_name: ""
app_pool_identity: "ApplicationPoolIdentity"
app_pool_username: ""
app_pool_password: ""
dotnet_version: "v4.0"
enable_32bit: false

# Configuration MSI
msi_arguments: "/quiet"

# Health Check
perform_health_check: true
health_check_path: "/"
health_check_retries: 5
health_check_delay: 30
expected_status_code: [200, 301, 302]

# Listes pour configurations avancées
config_files: []
config_transformations: []
ssl_bindings: []
directory_permissions: []