---
galaxy_info:
  author: DevOps Team
  description: Universal Linux package manager role
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 10
        - 11
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - package
    - management
    - linux
    - system

dependencies: []