---
# roles/apache2/tasks/main.yml
- name: Include installation tasks
  include_tasks: install.yml
  tags:
    - install

- name: Include configuration tasks
  include_tasks: configure.yml
  tags:
    - configure

- name: Include vhosts management tasks
  include_tasks: vhosts.yml
  tags:
    - vhosts