---
galaxy_info:
  author: "A&ECoding"
  description: "Rôle Ansible to Delete python on Windows"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - python -e target_version="X.X.X"
dependencies: []