---
- name: restart_iis
  win_shell: |
    iisreset /restart
  async: 120
  poll: 5

- name: restart_app_pool
  win_shell: |
    Import-Module WebAdministration
    if((Get-WebAppPoolState -Name "{{ iis_deploy_app_pool_name }}").Value -eq "Started") {
        Restart-WebAppPool -Name "{{ iis_deploy_app_pool_name }}"
    } else {
        Start-WebAppPool -Name "{{ iis_deploy_app_pool_name }}"
    }