---
galaxy_info:
  author: "A&ECoding"
  description: "Rôle Ansible to Install & Download Python version "
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - python -e python_version="X.X.X"
dependencies: []