# tasks file for csr_ca_sign
---
- name: Chec if CSR file exist
  stat:
    path: "{{ server_csr_file }}"
  register: csr_stat

- name: Failed if the CSR file doesn't exist
  fail:
    msg: "La CSR {{ server_csr_file }} est introuvable. Génère-la avant d'exécuter ce rôle."
  when: not csr_stat.stat.exists

- name: Sign CSR with CA local
  command: >
    openssl x509 -req -in {{ server_csr_file }} -CA {{ ca_cert_file }}
    -CAkey {{ ca_key_file }} -CAcreateserial -out {{ server_cert_file }}
    -days {{ cert_validity_days }} -sha256
  args:
    creates: "{{ server_cert_file }}"
  register: sign_ca

- name: Showing certificate generated
  debug:
    msg: "{{ sign_ca.stdout }}"
