---
- name: "Start - Démarrage des services (Windows)"
  win_shell: |
    cd "{{ project_path }}"
    docker-compose up -d
  when: ansible_os_family == "Windows"

- name: "Start - Démarrage des services (Linux)"
  shell: |
    cd "{{ project_path }}"
    docker-compose up -d
  when: ansible_os_family != "Windows"

- name: "Start - Attendre le démarrage"
  pause:
    seconds: 10

- name: "Start - Vérifier les services"
  win_shell: |
    cd "{{ project_path }}"
    docker-compose ps
  when: ansible_os_family == "Windows"
  register: services_status

- name: "Start - Vérifier les services (Linux)"
  shell: |
    cd "{{ project_path }}"
    docker-compose ps
  when: ansible_os_family != "Windows"
  register: services_status

- name: "Start - Afficher l'état"
  debug:
    var: services_status.stdout_lines