---
- name: "Stop - Arrêt des services (Windows)"
  win_shell: |
    cd "{{ project_path }}"
    docker-compose stop
  when: ansible_os_family == "Windows"

- name: "Stop - Arrêt des services (Linux)"
  shell: |
    cd "{{ project_path }}"
    docker-compose stop
  when: ansible_os_family != "Windows"

- name: "Stop - Confirmation"
  debug:
    msg: "🛑 Services arrêtés pour {{ project_name }}"