---
# handlers file for linux_apache2_reverse_proxy_home_assistant
- name: Restart Apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes

- name: Reload Apache
  systemd:
    name: apache2
    state: reloaded
    enabled: yes