---
# handlers file for apache2_reverse_proxy
- name: Restart Apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes

- name: Reload Apache
  systemd:
    name: apache2
    state: reloaded
    enabled: yes