---
# Variables par défaut pour apache2-management
action_apache: "status"

# Actions autorisées
apache_actions_allowed:
  - start
  - stop
  - restart
  - reload
  - status
  
# Mapping des services Apache selon la distribution
apache_service_names:
  Debian: apache2
  Ubuntu: apache2
  RedHat: httpd
  CentOS: httpd
  Fedora: httpd
  Rocky: httpd
  AlmaLinux: httpd
  Amazon: httpd
  SLES: apache2