---
# tasks file for windows_ollama_pull_manage
- name: Check if ollama is installed
  ansible.windows.win_shell: "where ollama"
  register: ollama_installed
  ignore_errors: yes
  changed_when: false

- name: Stop playbook if ollama not present
  fail:
    msg: "Ollama n'est pas installé. Veuillez l'installer avant de continuer."
  when: ollama_installed.rc != 0

- name: Pull Ollama models
  ansible.windows.win_shell: "ollama pull {{ item }}"
  with_items: "{{ ollama_models }}"
  register: pull_results
  changed_when: "'pulling' in pull_results.stdout"

# - name: Starting Model after pull
#   ansible.windows.win_shell: "start /B ollama run {{ item }}"
#   with_items: "{{ ollama_models }}"
#   async: 0
#   poll: 0
#   register: run_results
