---
- name: Packages Updating
  apt:
    update_cache: yes

- name: Install Apache2
  apt:
    name: apache2
    state: latest

- name: Starting apache after installation
  systemd:
    name: apache2
    state: started
    enabled: yes