---
# handlers file for windows_rust_install
- name: Actualiser les variables d'environnement
  win_shell: |
    $process = Get-Process -Id $PID
    foreach ($session in [System.Diagnostics.Process]::GetCurrentProcess().ProcessorAffinity) {
        if ($session.ProcessId -eq $process.Id) {
            $session.RefreshEnvironment()
        }
    }
  listen: refresh_env