---
# handlers file for windows_service_deploy_artifactory
- name: restart service
  win_service:
    name: "{{ service_name }}"
    state: restarted
  when: service_name is defined

- name: stop service
  win_service:
    name: "{{ service_name }}"
    state: stopped
  when: service_name is defined

- name: start service
  win_service:
    name: "{{ service_name }}"
    state: started
  when: service_name is defined
