---
# tasks file for windows_package_chocolatey_install
- name: Check installation of Chocolatey
  win_stat:
    path: C:\ProgramData\chocolatey\choco.exe
  register: choco_stat

- name: Exit if chocolatey isn't present
  fail:
    msg: "{{ chocolatey_missing_message }}"
  when: not choco_stat.stat.exists

- name: Debug
  debug:
    var: chocolatey_facts.ansible_facts.packages
    verbosity: 1

- name: Check if already installed
  set_fact:
    package_installed: >-
      {% if chocolatey_facts.ansible_facts.packages is defined %}
        {% set found = false %}
        {% for pkg in chocolatey_facts.ansible_facts.packages %}
          {% if pkg.id is defined and pkg.id|lower == package_name|lower %}
            {% set found = true %}
          {% elif pkg.package is defined and pkg.package|lower == package_name|lower %}
            {% set found = true %}
          {% elif pkg.name is defined and pkg.name|lower == package_name|lower %}
            {% set found = true %}
          {% endif %}
        {% endfor %}
        {{ found }}
      {% else %}
        false
      {% endif %}
    package_current_version: >-
      {% if chocolatey_facts.ansible_facts.packages is defined %}
        {% set version = '' %}
        {% for pkg in chocolatey_facts.ansible_facts.packages %}
          {% if (pkg.id is defined and pkg.id|lower == package_name|lower) or 
                (pkg.package is defined and pkg.package|lower == package_name|lower) or 
                (pkg.name is defined and pkg.name|lower == package_name|lower) %}
            {% set version = pkg.version if pkg.version is defined else '' %}
          {% endif %}
        {% endfor %}
        {{ version }}
      {% else %}
        ''
      {% endif %}
  when: package_name != ""

- name: Show package status
  debug:
    msg: "Le package {{ package_name }} {{ 'est déjà installé en version ' + package_current_version if package_installed else 'n''est pas installé' }}"
  when: package_name != ""

- name: Installation/Update of {{ package_name }} from Chocolatey
  win_chocolatey:
    name: "{{ package_name }}"
    version: "{{ package_version | default(omit) }}"
    state: "{{ package_state }}"
    force: "{{ force_install }}"
    source: "{{ chocolatey_source }}"
    timeout: "{{ chocolatey_timeout }}"
    package_params: "{{ install_params | default(omit) }}"
  register: choco_install
  when: package_name != ""

- name: Status of the installation
  debug:
    msg: "{{ package_name }} version {{ package_current_version if package_installed and not choco_install.changed else (package_version if package_version else 'latest') }} {{ 'est déjà installé' if package_installed and not choco_install.changed else 'a été installé avec succès' }}"
  when: package_name != ""