---
# vars file for linux_apache2_reverse_proxy_home_assistant
apache_proxy_config: "/etc/apache2/conf-available/reverseproxy.app"
## Vars files of http
apache_vhost_file: "/etc/apache2/sites-available/reverse_proxy_http.conf"
apache_vhost_link: "/etc/apache2/sites-enabled/reverse_proxy_http.conf"
## vars files of https/ssl 
apache_vhost_ssl_file: "/etc/apache2/sites-available/reverse_proxy_https.conf"
apache_vhost_ssl_link: "/etc/apache2/sites-enabled/reverse_proxy_https.conf"
## Certificate 
ssl_cert_file: "/etc/apache2/certificates/{{ server_name }}.crt"
ssl_cert_key_file: "/etc/apache2/certificates/{{ server_name }}.key"
ssl_cert_CA_file: "/etc/apache2/certificates/myCA.crt"
## proxy back-end var
proxy_pass: "http://192.168.1.16:8123/"
rewrite_home: "ws://192.168.1.16:8123/$1"
server_name: "reverseproxy.local"