---
- name: apache started
  debug:
    msg: "Apache a été démarré avec succès"

- name: apache stopped
  debug:
    msg: "Apache a été arrêté avec succès"

- name: apache restarted
  debug:
    msg: "Apache a été redémarré avec succès"

- name: apache reloaded
  debug:
    msg: "Apache a été rechargé avec succès"