---
- name: Check installation of Apache2
  apt:
    name: 
      - apache2
    state: present
    update_cache: yes

- name: Activate module proxy & SSL & Rewrite
  command: a2enmod proxy proxy_http ssl rewrite headers
  notify: Reload Apache

- name: Deployment of configuration file (reverseproxy.app)
  template:
    src: reverseproxy.app.j2
    dest: "{{ apache_proxy_config }}"
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache

- name: Deployment Vhost 8080
  template:
    src: vhost.conf.j2
    dest: "{{ apache_vhost_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache

- name: Deployment Vhost 4443 (SSL)
  template:
    src: vhost_ssl.conf.j2
    dest: "{{ apache_vhost_ssl_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache

- name: Add port 8080 in apache (ports.conf) in case with needed
  lineinfile:
    path: /etc/apache2/ports.conf
    line: "Listen 8080"
    state: present
  notify: Reload Apache

- name: Add port 4443 in apache (ports.conf)
  lineinfile:
    path: /etc/apache2/ports.conf
    line: "Listen 4443"
    state: present
  notify: Reload Apache

- name: Activate with a2ensite (SSL)
  command: a2ensite reverse_proxy_https.conf
  notify: Reload Apache