---
# tasks/install.yml - Version corrigée pour éviter le problème de symlink

- name: Install required packages
  apt:
    name:
      - unzip
      - curl
      - default-jdk
    state: present
    update_cache: yes
  tags:
    - install
    - packages

- name: Verify Java installation
  command: java -version
  register: java_version
  changed_when: false
  tags:
    - install
    - java

- name: Display Java version
  debug:
    var: java_version.stderr_lines
  tags:
    - install
    - java

- name: Create Keycloak user
  user:
    name: keycloak
    system: yes
    shell: /bin/bash
    home: /opt/keycloak
    create_home: no
  tags:
    - install
    - user

# Vérifier et supprimer le répertoire /opt/keycloak s'il existe déjà
- name: Check if /opt/keycloak exists and is a directory (not a symlink)
  stat:
    path: /opt/keycloak
  register: keycloak_dir
  tags:
    - install
    - directory

- name: Backup existing Keycloak directory if it exists and is not a symlink
  command: mv /opt/keycloak /opt/keycloak.bak
  args:
    removes: /opt/keycloak
  when: keycloak_dir.stat.exists and keycloak_dir.stat.isdir and not keycloak_dir.stat.islnk
  tags:
    - install
    - directory

# Créer le répertoire parent pour Keycloak
- name: Create parent directory for Keycloak installations
  file:
    path: /opt/keycloak-versions
    state: directory
    owner: keycloak
    group: keycloak
    mode: '0750'
  tags:
    - install
    - directory

- name: Ensure Keycloak directories have correct permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: keycloak
    group: keycloak
    mode: '0755'  # Mode plus permissif
    recurse: yes
  loop:
    - "/opt/keycloak"
    - "/opt/keycloak/data"
    - "/opt/keycloak/conf"
    - "/opt/keycloak/lib"
    - "/opt/keycloak/providers"
    - "/opt/keycloak/themes"
  tags:
    - install
    - permissions
    - configure

- name: Download Keycloak ZIP
  get_url:
    url: "https://github.com/keycloak/keycloak/releases/download/{{ keycloak_version }}/keycloak-{{ keycloak_version }}.zip"
    dest: "/tmp/keycloak-{{ keycloak_version }}.zip"
    mode: '0640'
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5
  tags:
    - install
    - download

- name: Extract Keycloak ZIP
  unarchive:
    src: "/tmp/keycloak-{{ keycloak_version }}.zip"
    dest: "/opt/keycloak-versions/"
    remote_src: yes
    owner: keycloak
    group: keycloak
    creates: "/opt/keycloak-versions/keycloak-{{ keycloak_version }}"
  tags:
    - install
    - extract

- name: Create symbolic link for Keycloak
  file:
    src: "/opt/keycloak-versions/keycloak-{{ keycloak_version }}"
    dest: /opt/keycloak
    state: link
    owner: keycloak
    group: keycloak
    force: yes
  tags:
    - install
    - symlink

- name: Ensure bin directory is executable
  file:
    path: /opt/keycloak/bin
    state: directory
    mode: '0750'
    recurse: yes
  tags:
    - install
    - permissions

- name: Cleanup temporary download file
  file:
    path: "/tmp/keycloak-{{ keycloak_version }}.zip"
    state: absent
  tags:
    - install
    - cleanup