---
# tasks/install.yml - Tâches d'installation de Keycloak

- name: Install required packages
  apt:
    name:
      - unzip
      - curl
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes
  tags:
    - install
    - packages

- name: Install OpenJDK 21
  block:
    - name: Add adoptium repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(lsb_release -cs) main"
        state: present
        filename: adoptium

    - name: Add adoptium gpg key
      apt_key:
        url: https://packages.adoptium.net/artifactory/api/gpg/key/public
        keyring: /usr/share/keyrings/adoptium.asc
        state: present

    - name: Install OpenJDK 21
      apt:
        name: temurin-21-jdk
        state: present
        update_cache: yes
  tags:
    - install
    - java

- name: Create Keycloak user
  user:
    name: keycloak
    system: yes
    shell: /sbin/nologin
    home: /opt/keycloak
    create_home: no
  tags:
    - install
    - user

- name: Create Keycloak installation directory
  file:
    path: /opt/keycloak
    state: directory
    owner: keycloak
    group: keycloak
    mode: '0750'
  tags:
    - install
    - directory

- name: Download Keycloak ZIP
  get_url:
    url: "https://github.com/keycloak/keycloak/releases/download/{{ keycloak_version }}/keycloak-{{ keycloak_version }}.zip"
    dest: "/tmp/keycloak-{{ keycloak_version }}.zip"
    mode: '0640'
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5
  tags:
    - install
    - download

- name: Extract Keycloak ZIP
  unarchive:
    src: "/tmp/keycloak-{{ keycloak_version }}.zip"
    dest: "/opt"
    remote_src: yes
    owner: keycloak
    group: keycloak
    creates: "/opt/keycloak-{{ keycloak_version }}"
  tags:
    - install
    - extract

- name: Create symbolic link for Keycloak
  file:
    src: "/opt/keycloak-{{ keycloak_version }}"
    dest: /opt/keycloak
    state: link
    owner: keycloak
    group: keycloak
  tags:
    - install
    - symlink

- name: Cleanup temporary download file
  file:
    path: "/tmp/keycloak-{{ keycloak_version }}.zip"
    state: absent
  tags:
    - install
    - cleanup