galaxy_info:
  author: "A&ECoding"
  description: "Rôle Ansible to manage container image on linux"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - linux
dependencies: []