---
# tasks file for windows_dotnet_install

- name: Check if .NET SDK are compatabile with var file (if not compatible, add the version on var file)
  ansible.builtin.assert:
    that:
      - sdk_version in dotnet_sdk_versions
    fail_msg: "Version .NET {{ sdk_version }} non supportée. Versions disponibles : {{ dotnet_sdk_versions.keys() | list }}"

- name: Check architecture of Windows 
  win_shell: $env:PROCESSOR_ARCHITECTURE
  register: architecture_result
  changed_when: false

- name: Check architecture from architecture_result
  set_fact:
    dotnet_arch: "{{ 
      'x64' if architecture_result.stdout | trim == 'AMD64' else 
      'x86' if architecture_result.stdout | trim == 'x86' else 
      'arm64' if architecture_result.stdout | trim == 'ARM64' else 
      'x64' 
    }}"

- name: Information from var file to install .NET {{ sdk_version }} SDK
  set_fact:
    dotnet_release: "{{ dotnet_sdk_versions[sdk_version].latest_release }}"
    dotnet_download_pr_id: "{{ dotnet_sdk_versions[sdk_version].download_pr_id }}"
    dotnet_download_hash: "{{ dotnet_sdk_versions[sdk_version].download_hash }}"

- name: Build link .NET SDK
  set_fact:
    dotnet_download_url: "https://download.visualstudio.microsoft.com/download/pr/{{ 
        dotnet_download_pr_id 
      }}/{{ 
        dotnet_download_hash 
      }}/dotnet-sdk-{{ dotnet_release }}-win-{{ dotnet_arch }}.exe"

- name: Install folder
  set_fact:
     dotnet_installer_path: "C:\\Temp\\dotnet-sdk-{{ dotnet_release }}-win-{{ dotnet_arch }}.exe"

- name: Create temp folder 
  win_file:
    path: C:\Temp
    state: directory

- name: Download .NET SDK
  win_uri:
    url: "{{ dotnet_download_url }}"
    dest: "{{ dotnet_installer_path }}"
    creates: "{{ dotnet_installer_path }}"
  register: download_check

- name: Installer .NET SDK
  win_command: '"{{ dotnet_installer_path }}"  /install /quiet /norestart'
  when: download_check is succeeded

- name: Check installation of .NET SDK
  win_command: dotnet --version
  register: dotnet_version_output
  changed_when: false

- name: Show the version has been installed
  debug:
    msg: 
      - "Version .NET installée : {{ dotnet_version_output.stdout_lines[0] }}"
      - "Architecture détectée : {{ dotnet_arch }}"
      - "URL de téléchargement : {{ dotnet_download_url }}"

- name: Clean-up installation folder
  win_file:
    path: "{{ dotnet_installer_path }}"
    state: absent