galaxy_info:
  author: "A&ECoding"
  description: "Rôle Ansible pour Start Service Windows"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - 2012R2
        - 2016
        - 2019
        - 2022
  galaxy_tags:
    - windows
    - service
    - system
dependencies: []
