---
# roles/security_report/tasks/ssh_audit.yml
- name: Check SSH configuration
  shell: |
    sshd -T 2>/dev/null | grep -E '^(permitrootlogin|passwordauthentication|protocol|port)'
  register: ssh_config
  changed_when: false
  failed_when: false

- name: Check for SSH keys with weak permissions
  find:
    paths: /home
    patterns: "*id_*"
    recurse: yes
    file_type: file
  register: ssh_keys

- name: Verify SSH key permissions
  stat:
    path: "{{ item.path }}"
  register: ssh_key_perms
  loop: "{{ ssh_keys.files }}"
  when: ssh_keys.files is defined
