---
# roles/security_report/tasks/user_audit.yml
- name: List users with UID 0 (root privileges)
  shell: |
    awk -F: '$3 == 0 {print $1}' /etc/passwd
  register: root_users
  changed_when: false

- name: Check for users without passwords
  shell: |
    awk -F: '$2 == "" {print $1}' /etc/shadow
  register: no_password_users
  changed_when: false
  failed_when: false

- name: Check for inactive users (no login for 90+ days)
  shell: |
    lastlog | awk '$2 !~ /Never/ && $4 != "" {
      cmd = "date -d \""$4" "$5" "$6" "$7"\" +%s 2>/dev/null"
      cmd | getline last_login
      close(cmd)
      if ((systime() - last_login) > 7776000) print $1
    }'
  register: inactive_users
  changed_when: false
  failed_when: false