---
# vars file for windows_service_deploy_artifactory
# Configuration Artifactory
artifactory_base_url: ""
artifactory_username: ""
artifactory_password: ""
artifactory_repository: ""
package_filename: ""
artifactory_package_url: "{{ artifactory_base_url }}/{{ artifactory_repository }}/{{ package_filename }}"

# Configuration de téléchargement
deploy_temp_dir: "C:\\temp\\deploy"
force_download: true
download_timeout: 300
delete_package_after_extract: false
cleanup_temp_files: true

# Configuration de sauvegarde
create_backup: true
backup_path: "C:\\backup"
recreate_service: false

# Configuration du service
service_name: ""
service_executable: ""
service_display_name: ""
service_description: "Service déployé via Ansible"
service_install_path: ""
service_start_mode: "auto"
service_username: ""
service_password: ""

# Configuration avancée du service
start_service_after_deploy: true
service_startup_timeout: 60
configure_failure_actions: true
failure_reset_period: 86400
failure_actions: "restart/60000/restart/60000/restart/60000"

# Configuration des packages
msi_arguments: "/quiet"
exe_arguments: "/S"

# Health Check
service_health_check_port: ""
service_health_check_host: "localhost"
health_check_timeout: 30

# Listes pour configurations avancées
config_files: []
config_transformations: []
service_dependencies: []
directory_permissions: []
