---
galaxy_info:
  author: A&E Coding
  description: Rôle pour tester la connectivité des serveurs Windows
  company: A&E Coding
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019
        - 2022

dependencies: []