---
- name: Installation of dependencies 
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Installation of Docker via script officiel
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  args:
    creates: /usr/bin/docker
  notify: restart docker