---
galaxy_info:
  author: A&E Coding
  description: Rôle pour tester la connectivité des serveurs Linux
  company: A&E Coding
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
        - 22.04
    - name: EL
      versions:
        - 7
        - 8
        - 9

dependencies: []